"""Role

Revision ID: 666385089a9f
Revises: ba6289dc4dbb
Create Date: 2018-02-20 21:07:27.267000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '666385089a9f'
down_revision = 'ba6289dc4dbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('default', sa.Boolean(), nullable=True))
    op.add_column('roles', sa.Column('permissions', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_column('roles', 'permissions')
    op.drop_column('roles', 'default')
    # ### end Alembic commands ###
